//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceHistoryWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryEntry
    {
        public int Id { get; set; }
        public int EndUserId { get; set; }
        public int CreatorId { get; set; }
        public string Summary { get; set; }
        public string Action { get; set; }
        public string Result { get; set; }
        public int DeviceId { get; set; }
        public string AdditionalNotes { get; set; }
        public System.DateTime Submitted { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime Closed { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual User EndUser { get; set; }
        public virtual User Creator { get; set; }
    }
}
